version: '3.9'

services:
  postgres:
    image: postgres:14.3-alpine
    restart: always
    shm_size: 128mb
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cadastro
    ports:
      - 5432:5432
      
  flyway:
    image: flyway/flyway
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/cadastro
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: 123456
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres
